### ISSUE TITLE
Feature request: QCEFF tables for models

### ISSUE THREAD

**Issue by hkershaw-brown** [NCAR/DART#824]
### Use case  
Users looking to use the QCEFF have to build their own QCEFF table, which seems to be a barrier to entry.

### Is your feature request related to a problem?  
Ease of use, 
- creating the table
- so many columns in the table

### Describe your preferred solution 
"Typical" qceff.csv for a model 
not sure if this would be per-model, or per component, e.g. ocean models have "typical" qceff options, atm models have "typical" qceff options. 
Is qceff a "set it and forget it" thing? bounded qty, bnrh?

### Describe any alternatives you have considered  
better interface for qceff, but this is unclear what is required. e.g. is it set and forget.

**Comment by hkershaw-brown** [comment]
Maybe an easier way to create tables?  Yaml where you only need to write the non-default values. 

```yaml
default:  # Default distribution for quantities not explicitly listed
  distribution: normal
  filter_kind: eakf

quantities:  # Explicitly defined quantity distributions
  temperature:   #default for temperature
    distribution: bnrh
    filter_kind: bnrhf
    upper_bound: 102

    probit_inf: # probit_inf has a special value for temperature
     upper_bound: 104

  pressure:
    distribution: lognormal

 ```

`yaml.in -> create_qceff_table -> table.out`

filter runs with table.out


The algorithm_info_mod default is normal, eakf. So if you wanted a default different for all quantities you have to list all qtys in the table.

qtys: 

Maybe group qts? e.g. all tracers get lognormal

```yaml
groups:
  lognormal_1:
    quantities: [co2, no2]
    distribution: lognormal
```    

All qtys you are interested in, default, special:

```yaml
quantities_to_set:
  - temperature
  - humidity
  - co2
  - no2
  - ozone
  - ch4
 
default:  
  distribution: bnrh
  filter_kind: bnhrf

groups:
  lognorm_gases:
    quantities: [co2, no2, ch4]
    distribution: lognormal

```
